# Generated by Django 5.0.4 on 2024-04-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=100)),
                ('pais_origen', models.CharField(max_length=100)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='imagenes_perfil/')),
            ],
        ),
    ]
